# version of docker-compose
version: '3.9'

services:
  database:
    container_name: postgres-container
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  cache:
    container_name: redis-container
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - ./cache:/data
